version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
    labels:
      - dependencies
